namespace EVIL.Lexical
{
    public enum TokenType
    {
        Empty = -1,
        
        Minus,
        Plus,
        Multiply,
        Divide,
        Modulo,
        BitwiseAnd,
        BitwiseOr,
        BitwiseXor,
        BitwiseNot,
        AsNumber,
        AsString,
        Length,
        Increment,
        Decrement,
        ShiftRight,
        ShiftLeft,
        
        Ellipsis,
        Associate,
        RightArrow,
        
        Dot,
        QuestionMark,
        DoubleQuestionMark,

        Assign,
        AssignAdd,
        AssignSubtract,
        AssignMultiply,
        AssignDivide,
        AssignModulo,
        AssignBitwiseAnd,
        AssignBitwiseOr,
        AssignBitwiseXor,
        AssignShiftRight,
        AssignShiftLeft,
        AssignCoalesce,

        DeepEqual,
        DeepNotEqual,
        Equal,
        NotEqual,
        LessThan,
        LessThanOrEqual,
        GreaterThan,
        GreaterThanOrEqual,

        LogicalNot,
        LogicalAnd,
        LogicalOr,

        Comma,
        Colon,
        DoubleColon,
        Semicolon,
        LParenthesis,
        RParenthesis,
        LBrace,
        RBrace,
        LBracket,
        RBracket,
        Array,
        Self,

        AttributeList,
        Identifier,

        Number,
        HexInteger,
        String,

        True,
        False,

        Fn,
        For,
        Do,
        While,
        Each,
        If,
        Elif,
        Else,
        Skip,
        Break,
        Ret,
        Val,
        In,
        Is,
        IsNot,
        Nil,
        TypeOf,
        Yield,
        Rw,
        NaN,
        Infinity,
        
        NilTypeCode,
        NumberTypeCode,
        StringTypeCode,
        BooleanTypeCode,
        TableTypeCode,
        ArrayTypeCode,
        FiberTypeCode,
        ChunkTypeCode,
        TypeCodeTypeCode,
        NativeFunctionTypeCode,
        NativeObjectTypeCode,
        
        Include,
        EOF
    }
}