name: Build EVIL front-end with runtime

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        runtime-identifier: [win-x64, linux-x64]
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: EVIL.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore solution
      run: dotnet restore
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build solution
      run: dotnet build -c $Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Run language tests
      working-directory: VirtualMachine/Tests/Ceres.LanguageTests/bin/net7.0/$Configuration
      run: VirtualMachine/Tests/Ceres.LanguageTests/bin/net7.0/$Configuration/Ceres.LanguageTests
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish to directory
      run: dotnet publish FrontEnd/EVIL.evil/EVIL.evil.csproj -c $Configuration -r $RuntimeIdentifier --no-self-contained -p:PublishSingleFile=true
      env:
        Configuration: ${{ matrix.configuration }}
        RuntimeIdentifier: ${{ matrix.runtime-identifier }}
        
    - name: Fetch front-end version
      id: package_version
      uses: MWin10/get-csproj-version-fork@v1.5.0
      with:
        file: FrontEnd/EVIL.evil/EVIL.evil.csproj

    - name: Pack artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: evil-${{ steps.package_version.outputs.version }}_${{ matrix.runtime-identifier }}-${{ matrix.configuration }}
        path: FrontEnd/EVIL.evil/bin/${{ matrix.configuration }}/net7.0/${{ matrix.runtime-identifier }}/publish
        if-no-files-found: error
        retention-days: 90
