name: Build NuGet packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore solution
      run: dotnet restore
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build solution
      run: dotnet build -c $Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Run language tests
      working-directory: VirtualMachine/Tests/EVIL.Ceres.LanguageTests/bin/${{ matrix.configuration }}/net7.0
      run: ./LanguageTestRunner tests --fail-on-compiler-errors --fail-on-test-errors
      
    - name: Create NuGet packages
      run: dotnet pack -o evil-nuget-latest

    - name: Upload built artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: evil-nuget_${{ matrix.configuration }}-latest
        path: evil-nuget-latest
        if-no-files-found: error
        retention-days: 90
