name: Build NuGet packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Restore solution
      run: dotnet restore
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build solution
      run: dotnet build -c $Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Run language tests (code optimizations disabled)
      working-directory: VirtualMachine/Tests/EVIL.Ceres.LanguageTests/bin/${{ matrix.configuration }}/net9.0
      run: ./LanguageTestRunner tests --fail-on-compiler-errors --fail-on-test-errors
      
    - name: Run language tests (code optimizations enabled)
      working-directory: VirtualMachine/Tests/EVIL.Ceres.LanguageTests/bin/${{ matrix.configuration }}/net9.0
      run: ./LanguageTestRunner tests --fail-on-compiler-errors --fail-on-test-errors -o   
    
    - name: Create NuGet packages
      run: |
        dotnet pack
        mkdir evil-nuget-latest
        mv PackageProjects/EVIL.Parser/bin/${{ matrix.configuration }}/*.nupkg evil-nuget-latest/
        mv PackageProjects/EVIL.VM/bin/${{ matrix.configuration }}/*.nupkg evil-nuget-latest/

    - name: Upload built artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: evil-nuget_${{ matrix.configuration }}-latest
        path: evil-nuget-latest
        if-no-files-found: error
        retention-days: 90
